### ISSUE TITLE
[Request] Improvement - Bump multiple posts!

### ISSUE THREAD

**Issue by rogerluan** [anonoz/NastyAssBumper#2]
Hey!

First of all, thank you for this amazing script. I was thinking about developing one, but unfortunately I had no idea on how to. 

I'd like to request a new improvement, please see if it's viable.

Idea: Be able to bump multiple posts across different groups. Instead of a single `POST_ID`, we could load the script with an array of `POST_ID`s.
It would be specially awesome if we could customize the interval between bumps to something like 1-3-6 hours or so. Or even "fire once only" upon user trigger. :) 

Thank you

**Comment by rogerluan** [comment]
EDIT: Nevermind... This script doesn't work anymore. Facebook removed `user_groups` permission probably due to bots spamming groups way too much. :( 

We'll have to think another way around hehe.

**Comment by anonoz** [comment]
Eh thanks for letting me know that it no longer works. Haven't been using it for quite a while.
